export enum ScreenNameEnum {
	ROOT = "ROOT",
	INICIO = "INICIO",
	SIGN_UP = "SIGN_UP",
	SIGN_IN = "SIGN_IN",
	ACTIVATE = "ACTIVATE",

	DASHBOARD_ADMIN = 'DASH_ADMIN',
	DASHBOARD_DEFAULT = 'DASH_DEFAULT'
}
